// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsotoDbFirst.Models
{
    public partial class CourseAssignment
    {
        [Key]
        [Column("InstructorID")]
        public int InstructorId { get; set; }
        [Key]
        [Column("CourseID")]
        public int CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("CourseAssignment")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(InstructorId))]
        [InverseProperty("CourseAssignment")]
        public virtual Instructor Instructor { get; set; }
    }
}